# Generated by Django 2.0.2 on 2018-09-26 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 2, 47, 9, 389077, tzinfo=utc)),
        ),
    ]
