# Generated by Django 2.0.2 on 2018-09-26 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20180926_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 2, 52, 27, 930984, tzinfo=utc)),
        ),
    ]
